from ._config import icon as config_icon
from ._reset import icon as reset_icon
from ._import import icon as import_icon
from ._export import icon as export_icon
from .mplcurvewidget_icon import icon as mplcurvewidget_icon
from .mplbasewidget_icon import icon as mplbasewidget_icon
from .mplerrorbarwidget_icon import icon as mplerrorbarwidget_icon
from .mplimagewidget_icon import icon as mplimagewidget_icon
from .mplbarwidget_icon import icon as mplbarwidget_icon
from ._tools import icon as tools_icon
from ._fitting import icon as fitting_icon
