from ._config import icon as config_icon
from ._reset import icon as reset_icon
from ._import import icon as import_icon
from ._export import icon as export_icon
from .mplcurvewidget_icon import icon as mplcurvewidget_icon
from .mplbasewidget_icon import icon as mplbasewidget_icon
from .mplerrorbarwidget_icon import icon as mplerrorbarwidget_icon
from ._home import icon as home_tool_icon
from ._zoom import icon as zoom_tool_icon
from ._exit import icon as exit_tool_icon
#from ._pan import icon as pan_tool_icon
from ._save import icon as save_tool_icon
from ._lasso import icon as lasso_tool_icon
from ._repos import icon as repos_tool_icon
from ._cross import icon as cross_tool_icon
from ._tools import icon as tools_icon
