icon = [
"48 48 4 1 ",
"  c #6B6B6B",
". c #6C6B6A",
"X c #6C6B6B",
"o c None",
"oooooooooooooooooooooo   ooooooooooooooooooooooo",
"oooooooooooooooooooooo    oooooooooooooooooooooo",
"oooooooooooooooooooooo    oooooooooooooooooooooo",
"oooooooooooooooooooooo    oooooooooooooooooooooo",
"ooooooooooooooooX  ooo    ooo  Xoooooooooooooooo",
"oooooooooooooo     ooo    ooo     oooooooooooooo",
"oooooooooooo       ooo    ooo       oooooooooooo",
"ooooooooooo        ooo    ooo        ooooooooooo",
"ooooooooooX        ooo    ooo         oooooooooo",
"oooooooo           ooo    ooo          ooooooooo",
"ooooooo            ooo    ooo           oooooooo",
"ooooooo            ooo    ooo            ooooooo",
"oooooo           ooooo    ooooo          Xoooooo",
"ooooo          ooooooo    ooooooo          ooooo",
"ooooo         oooooooo    oooooooo         ooooo",
"oooo         ooooooooo    ooooooooo         oooo",
"oooo        oooooooooo    oooooooooo        oooo",
"ooo         oooooooooo    oooooooooo         ooo",
"ooo        ooooooooooo    ooooooooooo        ooo",
"ooo        ooooooooooo    ooooooooooo        ooo",
"oo        oooooooooooo    oooooooooooo        oo",
"oo        oooooooooooooooooooooooooooo        oo",
"oo       XooooooooooooooooooooooooooooX       oo",
"oo       ooooooooooooooooooooooooooooo        oo",
"oo       oooooooooooooooooooooooooooooo       oo",
"oo       oooooooooooooooooooooooooooooo       oo",
"oo       oooooooooooooooooooooooooooooX       oo",
"oo       ooooooooooooooooooooooooooooo        oo",
"oo        oooooooooooooooooooooooooooo        oo",
"oo        oooooooooooooooooooooooooooo        oo",
"oo        oooooooooooooooooooooooooooo       ooo",
"ooo        oooooooooooooooooooooooooo        ooo",
"ooo        oooooooooooooooooooooooooo        ooo",
"ooo         oooooooooooooooooooooooo         ooo",
"oooo        Xoooooooooooooooooooooo.        oooo",
"oooo         ooooooooooooooooooooo          oooo",
"ooooo          oooooooooooooooooo          ooooo",
"ooooo          XooooooooooooooooX         oooooo",
"oooooo           Xoooooooooooo            oooooo",
"ooooooo             ooooooo.             ooooooo",
"oooooooo                                oooooooo",
"ooooooooo                              ooooooooo",
"oooooooooo                            oooooooooo",
"ooooooooooo                          ooooooooooo",
"ooooooooooooo                      ooooooooooooo",
"ooooooooooooooo                  ooooooooooooooo",
"oooooooooooooooooX           Xoooooooooooooooooo",
"oooooooooooooooooooooo    oooooooooooooooooooooo"
]
