icon = [
"48 48 3 1 ",
"  c #6A6B6B",
". c gray42",
"X c None",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXX......XXXX . XXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXX......XXX......XXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXX......XX........XXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXX......X..........XXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXX..................XXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXX.................. XXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXX....................XXXXXXXXXXXXXXXX",
"XXXXXXXXXXXX.................... XXXXXXXXXXXXXXX",
"XXXXXXXXXXXX......................XXXXXXXXXXXXXX",
"XXXXXXXXXXXX.......................XXXXXXXXXXXXX",
"XXXXXXXXXXX.........................XXXXXXXXXXXX",
"XXXXXXXXXX............................XXXXXXXXXX",
"XXXXXXXXX..............................XXXXXXXXX",
"XXXXXXXX................................XXXXXXXX",
"XXXXXXX................................. XXXXXXX",
"XXXXXX....................................XXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXX.....................................XXXXXX",
"XXXXX......................................XXXXX",
"XXXXX......................................XXXXX",
"XXXXX......................................XXXXX",
"XXXXX......................................XXXXX",
"XXXXX......................................XXXXX",
"XXXXX......................................XXXXX",
"XXXXX......................................XXXXX",
"XXXXX......................................XXXXX",
"XXXXX......................................XXXXX",
"XXXXX......................................XXXXX",
"XXXXX......................................XXXXX",
"XXXXX......................................XXXXX",
"XXXXX......................................XXXXX",
"XXXXX......................................XXXXX",
"XXXXX......................................XXXXX",
"XXXXX................XXXXXX................XXXXX",
"XXXXX...............XXXXXXX................XXXXX",
"XXXXX...............XXXXXXX................XXXXX",
"XXXXX...............XXXXXXX................XXXXX",
"XXXXX...............XXXXXXX................XXXXX",
"XXXXX...............XXXXXXX................XXXXX",
"XXXXX...............XXXXXXX................XXXXX",
"XXXXX...............XXXXXXX................XXXXX",
"XXXXX...............XXXXXXX................XXXXX",
"XXXXX...............XXXXXXX................XXXXX",
"XXXXX...............XXXXXXX................XXXXX",
"XXXXX...............XXXXXXXX..............XXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
]
