# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_kbdhelp.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(269, 491)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setContentsMargins(6, 6, 6, 6)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.label_14 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(False)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("")
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 20, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet(
            "QLabel {\n"
            "    padding:0.1em 0.5em;\n"
            "    font-family:Arial,Helvetica,sans-serif;\n"
            "    background-color:#F7F7F7;\n"
            "    color:#333;    \n"
            "    border-radius:2px;\n"
            "    border: 1px solid gray;\n"
            "    margin:0 0.1em;\n"
            "    line-height: 1.4;\n"
            "}")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 12, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setStyleSheet(
            "QLabel {\n"
            "    padding:0.1em 0.5em;\n"
            "    font-family:Arial,Helvetica,sans-serif;\n"
            "    background-color:#F7F7F7;\n"
            "    color:#333;    \n"
            "    border-radius:2px;\n"
            "    border: 1px solid gray;\n"
            "    margin:0 0.1em;\n"
            "    line-height: 1.4;\n"
            "}")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 6, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 1, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setItalic(False)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 8, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setStyleSheet(
            "QLabel {\n"
            "    padding:0.1em 0.5em;\n"
            "    font-family:Arial,Helvetica,sans-serif;\n"
            "    background-color:#F7F7F7;\n"
            "    color:#333;    \n"
            "    border-radius:2px;\n"
            "    border: 1px solid gray;\n"
            "    margin:0 0.1em;\n"
            "    line-height: 1.4;\n"
            "}")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 14, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setStyleSheet(
            "QLabel {\n"
            "    padding:0.1em 0.5em;\n"
            "    font-family:Arial,Helvetica,sans-serif;\n"
            "    background-color:#F7F7F7;\n"
            "    color:#333;    \n"
            "    border-radius:2px;\n"
            "    border: 1px solid gray;\n"
            "    margin:0 0.1em;\n"
            "    line-height: 1.4;\n"
            "}")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 13, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setStyleSheet(
            "QLabel {\n"
            "    padding:0.1em 0.5em;\n"
            "    font-family:Arial,Helvetica,sans-serif;\n"
            "    background-color:#F7F7F7;\n"
            "    color:#333;    \n"
            "    border-radius:2px;\n"
            "    border: 1px solid gray;\n"
            "    margin:0 0.1em;\n"
            "    line-height: 1.4;\n"
            "}")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(False)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("")
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet(
            "QLabel {\n"
            "    padding:0.1em 0.5em;\n"
            "    font-family:Arial,Helvetica,sans-serif;\n"
            "    background-color:#F7F7F7;\n"
            "    color:#333;    \n"
            "    border-radius:2px;\n"
            "    border: 1px solid gray;\n"
            "    margin:0 0.1em;\n"
            "    line-height: 1.4;\n"
            "}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 10, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(False)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("")
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 13, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(False)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("")
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 6, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setItalic(False)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 21, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(False)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("")
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 15, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(False)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("")
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(False)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 10, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(False)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("")
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 12, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(False)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("")
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 7, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setStyleSheet(
            "QLabel {\n"
            "    padding:0.1em 0.5em;\n"
            "    font-family:Arial,Helvetica,sans-serif;\n"
            "    background-color:#F7F7F7;\n"
            "    color:#333;    \n"
            "    border-radius:2px;\n"
            "    border: 1px solid gray;\n"
            "    margin:0 0.1em;\n"
            "    line-height: 1.4;\n"
            "}")
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 7, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(False)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("")
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 11, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setStyleSheet(
            "QLabel {\n"
            "    padding:0.1em 0.5em;\n"
            "    font-family:Arial,Helvetica,sans-serif;\n"
            "    background-color:#F7F7F7;\n"
            "    color:#333;    \n"
            "    border-radius:2px;\n"
            "    border: 1px solid gray;\n"
            "    margin:0 0.1em;\n"
            "    line-height: 1.4;\n"
            "}")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 8, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 0, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft
                                   | QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 0, 1, 1, 1)
        self.line = QtWidgets.QFrame(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setStyleSheet(
            "QLabel {\n"
            "    padding:0.1em 0.5em;\n"
            "    font-family:Arial,Helvetica,sans-serif;\n"
            "    background-color:#F7F7F7;\n"
            "    color:#333;    \n"
            "    border-radius:2px;\n"
            "    border: 1px solid gray;\n"
            "    margin:0 0.1em;\n"
            "    line-height: 1.4;\n"
            "}")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 11, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setStyleSheet(
            "QLabel {\n"
            "    padding:0.1em 0.5em;\n"
            "    font-family:Arial,Helvetica,sans-serif;\n"
            "    background-color:#F7F7F7;\n"
            "    color:#333;    \n"
            "    border-radius:2px;\n"
            "    border: 1px solid gray;\n"
            "    margin:0 0.1em;\n"
            "    line-height: 1.4;\n"
            "}")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 15, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setStyleSheet(
            "QLabel {\n"
            "    padding:0.1em 0.5em;\n"
            "    font-family:Arial,Helvetica,sans-serif;\n"
            "    background-color:#F7F7F7;\n"
            "    color:#333;    \n"
            "    border-radius:2px;\n"
            "    border: 1px solid gray;\n"
            "    margin:0 0.1em;\n"
            "    line-height: 1.4;\n"
            "}")
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 21, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(False)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("")
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 14, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setStyleSheet(
            "QLabel {\n"
            "    padding:0.1em 0.5em;\n"
            "    font-family:Arial,Helvetica,sans-serif;\n"
            "    background-color:#F7F7F7;\n"
            "    color:#333;    \n"
            "    border-radius:2px;\n"
            "    border: 1px solid gray;\n"
            "    margin:0 0.1em;\n"
            "    line-height: 1.4;\n"
            "}")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 4, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(Dialog)
        self.label_32.setObjectName("label_32")
        self.gridLayout.addWidget(self.label_32, 18, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(Dialog)
        self.label_31.setStyleSheet(
            "QLabel {\n"
            "    padding:0.1em 0.5em;\n"
            "    font-family:Arial,Helvetica,sans-serif;\n"
            "    background-color:#F7F7F7;\n"
            "    color:#333;    \n"
            "    border-radius:2px;\n"
            "    border: 1px solid gray;\n"
            "    margin:0 0.1em;\n"
            "    line-height: 1.4;\n"
            "}")
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout.addWidget(self.label_31, 18, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setStyleSheet(
            "QLabel {\n"
            "    padding:0.1em 0.5em;\n"
            "    font-family:Arial,Helvetica,sans-serif;\n"
            "    background-color:#F7F7F7;\n"
            "    color:#333;    \n"
            "    border-radius:2px;\n"
            "    border: 1px solid gray;\n"
            "    margin:0 0.1em;\n"
            "    line-height: 1.4;\n"
            "}")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 20, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(Dialog)
        self.label_29.setStyleSheet(
            "QLabel {\n"
            "    padding:0.1em 0.5em;\n"
            "    font-family:Arial,Helvetica,sans-serif;\n"
            "    background-color:#F7F7F7;\n"
            "    color:#333;    \n"
            "    border-radius:2px;\n"
            "    border: 1px solid gray;\n"
            "    margin:0 0.1em;\n"
            "    line-height: 1.4;\n"
            "}")
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 9, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(Dialog)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 9, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_14.setText(_translate("Dialog", "Show this window"))
        self.label_2.setText(_translate("Dialog", "m"))
        self.label_25.setText(_translate("Dialog", "a,y"))
        self.label_22.setText(_translate("Dialog", "Change colormap"))
        self.label_19.setText(_translate("Dialog", "s"))
        self.label_6.setText(_translate("Dialog", "r"))
        self.label_3.setText(_translate("Dialog", "a"))
        self.label_24.setText(
            _translate("Dialog",
                       "<html><head/><body><p>Auto X scale</p></body></html>"))
        self.label.setText(_translate("Dialog", "g"))
        self.label_13.setText(_translate("Dialog", "Force refresh"))
        self.label_26.setText(
            _translate("Dialog",
                       "<html><head/><body><p>Auto Y scale</p></body></html>"))
        self.label_18.setText(_translate("Dialog", "Close this window"))
        self.label_12.setText(_translate("Dialog", "Tight layout on/off"))
        self.label_10.setText(
            _translate(
                "Dialog",
                "<html><head/><body><p>Auto X&amp;Y scale</p></body></html>"))
        self.label_8.setText(_translate("Dialog", "Turn on/off grid"))
        self.label_9.setText(_translate("Dialog", "Turn on/off minor ticks"))
        self.label_28.setText(
            _translate(
                "Dialog",
                "<html><head/><body><p>Turn on/off auto scale</p></body></html>"
            ))
        self.label_27.setText(_translate("Dialog", "a,a"))
        self.label_11.setText(_translate("Dialog", "Turn on/off legend"))
        self.label_21.setText(_translate("Dialog", "c"))
        self.label_15.setText(_translate("Dialog", "Key"))
        self.label_16.setText(_translate("Dialog", "Function"))
        self.label_4.setText(_translate("Dialog", "l"))
        self.label_5.setText(_translate("Dialog", "t"))
        self.label_17.setText(_translate("Dialog", "ESC"))
        self.label_20.setText(_translate("Dialog", "Change y-axis scale"))
        self.label_23.setText(_translate("Dialog", "a,x"))
        self.label_32.setText(_translate("Dialog", "Show/close toolbar"))
        self.label_31.setText(_translate("Dialog", "t,t"))
        self.label_7.setText(_translate("Dialog", "?"))
        self.label_29.setText(_translate("Dialog", "c,c"))
        self.label_30.setText(_translate("Dialog", "Open style configuration"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
